service: employee-serverless-restapi

provider:
  name: aws
  runtime: java8
  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1
  #This adds the required permissions to the IAM Lambda role to access DynamoDB
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["employeeTable", "Arn" ] }

#You can add your environment variables here
environment:
   variable1: value1

package:
  artifact: target/employee-serverless-restapi-${self:provider.stage}.jar

functions:
  createEmployee:
    handler: com.serverless.CreateEmployeeHandler
    events:
      - http:
          path: employee
          method: post
  getEmployees:
    handler: com.serverless.GetEmployeeHandler
    events:
      - http:
          path: employee
          method: get

resources:
  Resources:
    #Create DynamoDB Table
    employeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees-dev
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          #DynamoDB Partition Key
          - AttributeName: id
            KeyType: HASH
          #DynamoDB Sort Key
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
